name       : libnl
version    : 3.2.21
release    : 4
source     :
    - https://github.com/thom311/libnl/archive/libnl3_2_21.tar.gz : 1526f2cda3bc03af75d8ff993d2ffa59702c9fcac658cf65e7b404594569c70f
homepage   : http://www.infradead.org/~tgr/libnl
license    : LGPL-2.1-or-later
component  : network.base
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
summary    : a collection of libraries providing APIs to netlink protocol based Linux kernel interfaces.
description: |
    Netlink is a IPC mechanism primarly between the kernel and user space processes. It was designed to be a more flexible successor to ioctl to provide mainly networking related kernel configuration and monitoring interfaces.
setup      : |
    %reconfigure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
