name        : libnl
version     : 3.2.21
release     : 3
source      :
    - http://www.infradead.org/~tgr/libnl/files/libnl-3.2.21.tar.gz : 2dc80f043116ec8610d9d418f5f5e9283f3d9a3a48b8d51a8cb0146b3f279604
homepage    : http://www.infradead.org/~tgr/libnl
license     :
    - LGPL-2.1
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
summary     : a collection of libraries providing APIs to netlink protocol based Linux kernel interfaces.
description : |
    Netlink is a IPC mechanism primarly between the kernel and user space processes. It was designed to be a more flexible successor to ioctl to provide mainly networking related kernel configuration and monitoring interfaces.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
